# Generated by Django 3.1.6 on 2021-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('_type', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
