# Generated by Django 3.1.6 on 2021-03-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
