# Generated by Django 3.1.6 on 2021-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_plan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
