# Generated by Django 3.1.6 on 2021-03-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invitetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitetoken',
            old_name='biz',
            new_name='biz_acct',
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
    ]
