# Generated by Django 3.1.6 on 2021-03-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210313_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetoken',
            name='biz_acct',
        ),
    ]
