# Generated by Django 3.1.6 on 2021-03-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_invitetoken_biz_acct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BizAccount',
        ),
    ]
