# Generated by Django 3.1.6 on 2021-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_bizaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
