# Generated by Django 3.1.6 on 2021-03-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plan_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='video',
        ),
    ]
