# Generated by Django 3.1.6 on 2021-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
