# Generated by Django 3.1.6 on 2021-03-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
