# Generated by Django 3.1.6 on 2021-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
