# Generated by Django 3.1.6 on 2021-03-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='plan',
            new_name='has_plan',
        ),
    ]
