# Generated by Django 3.1.6 on 2021-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210313_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_plan',
            field=models.BooleanField(default=False),
        ),
    ]
