# Generated by Django 3.1.6 on 2021-03-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_biz_acct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biz_acct',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plantype',
        ),
    ]
